# Generated by Django 4.1.3 on 2022-11-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('incident_desc', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('incident_loc', models.TextField()),
                ('initial_severity', models.CharField(max_length=100)),
                ('suspected_cause', models.TextField()),
                ('immediate_actions_taken', models.TextField()),
                #('sub_incident_types', models.CharField(max_length=100)),
            ],
        ),
    ]
